name: Deploy Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deploy to pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - run: yarn --frozen-lockfile

      - run: yarn build:examples

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: build
          single-commit: true
