name: Run Checks

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Run Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: yarn

      - run: yarn --frozen-lockfile

      - run: yarn lint

      - run: yarn build
